/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
	const Activity: typeof import("react").Activity;
	const Badge: typeof import("./app/components/ui/badge").Badge;
	const Button: typeof import("./app/components/ui/button").Button;
	const Card: typeof import("./app/components/ui/card").Card;
	const CardAction: typeof import("./app/components/ui/card").CardAction;
	const CardContent: typeof import("./app/components/ui/card").CardContent;
	const CardDescription: typeof import("./app/components/ui/card").CardDescription;
	const CardFooter: typeof import("./app/components/ui/card").CardFooter;
	const CardHeader: typeof import("./app/components/ui/card").CardHeader;
	const CardTitle: typeof import("./app/components/ui/card").CardTitle;
	const Fragment: typeof import("react").Fragment;
	const Nav: typeof import("./app/components/nav").Nav;
	const Providers: typeof import("./app/components/providers").Providers;
	const Separator: typeof import("./app/components/ui/separator").Separator;
	const Suspense: typeof import("react").Suspense;
	const ThemeToggle: typeof import("./app/components/theme-toggle").ThemeToggle;
	const badgeVariants: typeof import("./app/components/ui/badge").badgeVariants;
	const buttonVariants: typeof import("./app/components/ui/button").buttonVariants;
	const cache: typeof import("react").cache;
	const cacheSignal: typeof import("react").cacheSignal;
	const createContext: typeof import("react").createContext;
	const createRef: typeof import("react").createRef;
	const forwardRef: typeof import("react").forwardRef;
	const lazy: typeof import("react").lazy;
	const memo: typeof import("react").memo;
	const startTransition: typeof import("react").startTransition;
	const use: typeof import("react").use;
	const useActionState: typeof import("react").useActionState;
	const useCallback: typeof import("react").useCallback;
	const useContext: typeof import("react").useContext;
	const useDebugValue: typeof import("react").useDebugValue;
	const useDeferredValue: typeof import("react").useDeferredValue;
	const useEffect: typeof import("react").useEffect;
	const useEffectEvent: typeof import("react").useEffectEvent;
	const useId: typeof import("react").useId;
	const useImperativeHandle: typeof import("react").useImperativeHandle;
	const useInsertionEffect: typeof import("react").useInsertionEffect;
	const useLayoutEffect: typeof import("react").useLayoutEffect;
	const useMemo: typeof import("react").useMemo;
	const useOptimistic: typeof import("react").useOptimistic;
	const useReducer: typeof import("react").useReducer;
	const useRef: typeof import("react").useRef;
	const useState: typeof import("react").useState;
	const useSyncExternalStore: typeof import("react").useSyncExternalStore;
	const useTransition: typeof import("react").useTransition;
}
