packages:
  - apps/*
  - packages/*
catalog:
  dotenv: ^17.3.1
  zod: ^4.3.6
  typescript: ^5.9.3
  "@types/bun": ^1.3.9
  elysia: ^1.4.25
  "@orpc/server": ^1.13.5
  "@orpc/openapi": ^1.13.5
  "@orpc/zod": ^1.13.5
  "@libsql/client": ^0.17.0
  libsql: ^0.5.22
  "@orpc/client": ^1.13.5
